### ISSUE TITLE
Release versioning

### ISSUE THREAD

**Issue by arichiardi** [boot-clj/boot-figreload#11]
Hello folks!

I am opening this issue in order to understand what is the best course of action for releasing `boot-figreload` now that it seems kind of time for getting rid of `-SNAPSHOT`.

The thing is, I was thinking of releasing following `lein-figwheel` stable versions, because being figwheel a huge project there might be things that work in a stable version and don't work in some other stable version. If we tie `boot-figreload` and `lein-figwheel` the version makes clear what we are running.

Objections? Better ideas?

I have already tried `0.5.11` and it works very well so I might as well start from that one, bumping this accordingly.

/cc @kommen @mbuczko and everyone interested

Thanks!

**Comment by DonyorM** [comment]
Tying the versions together seems like a good idea. It will also make it easier to search out issues with the underlying version of figwheel, rather than just opening relatively unrelated issues here.

**Comment by kommen** [comment]
I'm also for going with the same versions as figwheel.

**Comment by arichiardi** [comment]
Ok first version released: https://clojars.org/powerlaces/boot-figreload/versions/0.5.9
