### ISSUE TITLE
configuration conflict with boot-cljs

### ISSUE THREAD

**Issue by leroix** [boot-clj/boot-figreload#3]
To set the path prefix for files output by boot-cljs, they recommend storing the .cljs.edn file in the path where you'd like the files to be output. boot-figreload names the `figwheel.connect...` namespace according to the `:id`. If I store the .cljs.edn file at `js/dev.cljs.edn`, the figwheel namespace becomes `figwheel.connect.js/dev`. This causes a compilation error.

**Comment by mbuczko** [comment]
to be precise compilation error look like this:

    No such namespace: figwheel.connect.scripts/main,  could not locate
    figwheel/connect/scripts_SLASH_main.cljs, figwheel/connect/scripts_SLASH_main.cljc,
    or Closure namespace "main" in file boot/cljs/main31906.cljs

for main.cljs.edn in scripts/ dir

**Comment by arichiardi** [comment]
Thanks for reporting, I will check what is going on.

**Comment by arichiardi** [comment]
Good ol' bug here, I'll fix it asap

**Comment by arichiardi** [comment]
So figwheel does not have the concept of configuration in different folders, which means that the build id will always be the name of the file with extension `.cljs.edn`. I am correcting the problem.

**Comment by arichiardi** [comment]
If you folks can confirm it is fixed it would be awesome, I have a repro repo [here](https://github.com/arichiardi/figreload-demo/tree/boot-cljs-152) where it seems to be ok.

**Comment by mbuczko** [comment]
works perfectly. thanks for your time on fixing this issue. looks like boot-figreload became better than figwheel itself :)

**Comment by arichiardi** [comment]
Oh well, thanks for the support, but I think there is still a lot to do :1st_place_medal:
